### ISSUE TITLE
Missing printf.c and steps of combining a2-boot with a2-code

### ISSUE THREAD

**Issue by shgoupf** [openpower-cores/a2-code#3]
Dear maintainers,

I'm trying to build an image that can run on a2o, however I am not able to find the steps of combining the boot image of `a2-boot` with the programs (ops) of `a2-code`. 

I am not able to find `printf.c` as well.

Could anyone please help?

BTW, I also checked https://github.com/OpenPOWERFoundation, no clue.

**Comment by openpowerwtf** [comment]
Hi @shgoupf!

1. printf.c - I was using one of the github minimal versions (good enough to do simple printf's).

2. Does the c/ops/build script not work?  It was just good enough to get the original FPGA test running - I will be changing the process to use loader script, etc.   I have finally gotten some of the repos moved to https://github.com/OpenPOWERFoundation.  A2O is now there and I have included my latest updates (source changes for open compilers, initial cocotb testing, etc.).  The memory build is not set up yet but it will be more like a normal obj/exe creation process (Litex, etc.).

**Comment by openpowerwtf** [comment]
A2O is now being developed in https://github.com/OpenPOWERFoundation/a2o.  

It is running a sample kernel/bios/test with cocotb and icarus.  Continuing there to get verilator working.
